'use strict';var qx={TAB:0,Mj:1,cn:2},rx=function(a){Bb("MediaRouter.CastStreaming.Start.Success",a,qx)};var sx=gb("mr.mirror.cast.LogUploader"),ux=function(a,b,c){tx("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?reportid=&q="+encodeURIComponent("UserComments='"+b+"'"):""},tx=function(a,b,c,d){if(0==b.size)sx.info("Trying to upload an empty file to Crash"),d&&d(null);else{var e=new FormData;e.append("prod","Cast");e.append("ver",chrome.runtime.getManifest().version);e.append(a,b);c&&e.append("comments",c);Uu("https://clients2.google.com/cr/report",function(a){a=a.target;
var c=null;dv(a)?(c=ev(a),sx.info("Upload to Crash succeeded: "+c)):sx.info("Upload to Crash failed. HTTP status: "+a.Oa());d&&d(c)},"POST",e,void 0,3E4)}};var vx=function(){this.b=0;kj(this)},xx=function(){wx||(wx=new vx);return wx},yx=function(){var a=xx(),b={fraction:.01,autoSubmitTimeLimitMillis:6048E5},c=b.autoSubmitTimeLimitMillis,d=Date.now();return a.b&&c&&d-a.b<c?!1:Math.random()<b.fraction};vx.prototype.Aa=function(){return"mirror.cast.LogUtils"};vx.prototype.fb=function(){return[void 0,{lastAutoSubmitMillis:this.b}]};vx.prototype.eb=function(){var a=ij(this);this.b=a&&a.lastAutoSubmitMillis||0};var wx=null;gb("mr.mirror.cast.LogUtils");var zx={Qv:"OFFER",Or:"ANSWER",rw:"PRESENTATION",Ft:"GET_STATUS",Cx:"STATUS_RESPONSE",Et:"GET_CAPABILITIES",ns:"CAPABILITIES_RESPONSE",cx:"RPC"};var Ax=function(){this.capabilities=this.status=this.b=this.error=this.rpc=this.result=this.type=this.f=this.sessionId=null},Dx=function(a){try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var b;Bx(JSON.parse(a),function(a){b=Cx(a)},function(){throw Error("non-Object result from JSON parse");});return b}catch(d){var c=d instanceof SyntaxError?"JSON parse error: "+d.message:"Type coercion error: "+d.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(c+". Input was "+a);},Cx=function(a){var b=new Ax;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Ex(a.seqNum,function(a){b.f=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),d=k(Object.keys(zx)),e=d.next();!e.done;e=d.next())if(zx[e.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));if("rpc"in a){if("string"!==typeof a.rpc)throw Error('"rpc" must be a String containing a base64 payload');b.rpc=new Uint8Array([].concat(m(atob(a.rpc))).map(function(a){return a.charCodeAt(0)}))}Bx(a.error,function(a){b.error=Fx(a)},function(){throw Error('"error" must be an Object');});Bx(a.answer,function(a){b.b=Gx(a)},function(){throw Error('"answer" must be an Object');});Bx(a.status,function(a){b.status=Hx(a)},function(){throw Error('"status" must be an Object');
});Bx(a.capabilities,function(a){b.capabilities=Ix(a)},function(){throw Error('"capabilities" must be an Object');});return b},Bx=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Ex=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Jx=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Kx=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Lx=function(){this.j=null;this.b=[];this.f=
[];this.g=this.h=this.l=null},Gx=function(a){var b=new Lx;Ex(a.udpPort,function(a){b.j=a},function(){throw Error('"answer.udpPort" must be a number');});Jx(a.sendIndexes,function(a){b.b=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Jx(a.ssrcs,function(a){b.f=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.l=String(a.IV));"receiverGetStatus"in a&&(b.h="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in a&&(b.g=String(a.castMode));
return b},Mx=function(){this.details=this.description=this.code=null},Fx=function(a){var b=new Mx;Ex(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Bx(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},Nx=function(){this.f=this.b=null},Hx=function(a){var b=new Nx;Ex(a.wifiSnr,function(a){b.b=a},function(){throw Error('"status.wifiSnr" must be a number');
});Jx(a.wifiSpeed,function(a){b.f=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},Ox=function(){this.f=this.b=null},Ix=function(a){var b=new Ox;Kx(a.mediaCaps,function(a){b.b=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.f=a.map(function(a){var c;Bx(a,function(a){c=Px(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return c})}return b},Qx=function(){this.g=this.o=this.l=this.j=this.u=this.b=this.A=this.f=this.initDataTypes=this.h=null},Px=function(a){var b=new Qx;"keySystemName"in a&&(b.h=String(a.keySystemName));Kx(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Kx(a.codecs,function(a){b.f=a},function(){throw Error('"capabilities.codecs" must be an array');});Kx(a.secureCodecs,function(a){b.A=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Kx(a.audioRobustness,function(a){b.b=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Kx(a.videoRobustness,function(a){b.u=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.j=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.l=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.o=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.g=String(a.distinctiveIdentifierSupport));return b};var Rx=function(a){this.m=gb("mr.mirror.cast.MessageDispatcher");this.h=a;this.b=null;this.f=new Map;this.g=0},Sx=function(a,b,c){if(a.f.has(b))throw Error("Attempt to multiple-subscribe to the same response type: "+b);a.f.set(b,c);a.g=0;nb(a.m,"Added subscriber for "+b+"-type messages.");a.b||(a.b=ow(a.h),a.b.onMessage=a.j.bind(a))},Tx=function(a,b){a.f.delete(b)&&nb(a.m,function(){return"Removed subscriber of "+b+"-type messages."});0==a.f.size&&a.b&&(a.b.Ua(),a.b=null)};
Rx.prototype.sendMessage=function(a){return this.b?"RPC"==a.type?this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.remoting"}):this.b.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"}):Promise.reject(Error("Require at least one subscriber before sending messages."))};
var Ux=function(a,b,c,d,e){var f=null,h=function(){Tx(a,c);null!=f&&(clearTimeout(f),f=null)};try{Sx(a,c,function(a){e(a)&&h()})}catch(l){e(null,l);return}f=setTimeout(function(){h();e(null,Error("timeout"))},d);a.sendMessage(b).catch(function(a){h();e(null,a)})};
Rx.prototype.j=function(a){if(a&&"string"===typeof a.namespace_&&a.namespace_.startsWith("urn:x-cast:com.google.cast.")){do{var b=void 0;try{b=Dx(a.data)}catch(d){b=d.message;break}if(b.type){var c=this.f.get(b.type);if(c)try{c(b);return}catch(d){b="Error thrown during delivery. Response was: "+(JSON.stringify(b)+". Error from subscriber callback ")+("was: "+d.message+".")}else b="Message was ignored: "+JSON.stringify(b)}else b="Message did not include response type: "+JSON.stringify(b)}while(0);
10>this.g?this.m.F(b):nb(this.m,b);++this.g}};var Vx=function(){this.b=Promise.resolve(1)},Xx=function(a,b,c){return Wx(a,function(a){return a==b},c)},Yx=function(a,b){var c=[3,4];return Wx(a,function(a){return-1!=c.indexOf(a)},b)},Zx=function(a,b){a.b=a.b.catch(function(){return 1});return Wx(a,function(){return!0},b)},Wx=function(a,b,c){var d,e,f=new Promise(function(a,c){d=a;e=c});a.b=a.b.then(function(a){if(!b(a))return e(Error("Operation requires a different starting checkpoint than "+a)),Promise.resolve(a);var f=new $x(a);try{var h=c(f)}catch(y){h=
Promise.reject(y)}return h.then(function(a){return d(a)},function(a){return e(a)}).then(function(){if(null===f.b)throw Error("A prior operation that started at "+(a+" did not complete."));return f.b})},function(a){e(a);throw a;});return f},$x=function(a){this.f=a;this.b=null},ay=function(a,b){a.b="number"===typeof b?b:a.f};var by=chrome.cast.streaming,dy=function(a,b,c,d,e){this.G=a.sessionId;this.u=a.If;this.K=a.Od;this.g=b;this.N=c;this.D=d;this.M=cy(e,"onAnswer",this.u);this.Ca=cy(e,"onSessionStop",this.u);this.m=gb("mr.mirror.cast.StreamingLaunchWorkflow");this.B=new Vx;this.o=this.w=this.A=this.f=this.b=this.l=this.j=this.h=null};
dy.prototype.start=function(a,b,c){var d=this;if(!a&&!b)return Promise.reject(Error("No tracks to stream"));var e=a instanceof ey,f=b instanceof ey;(e&&b&&!f||f&&a&&!e)&&Gb("Mixing remoting and non-remoting tracks");return Xx(this.B,1,function(e){d.h=a;d.j=b;d.l=c;d.m.info(function(){return"Launching streaming for "+fy(d)+" "+("to a "+d.K+".")});return gy(d).then(d.C.bind(d)).then(function(a){return hy(d,a).then(function(c){d.M();var b=iy(d,c,a);d.b=jy(d,d.b,b);d.f=jy(d,d.f,b);if(!d.b&&!d.f)throw Error("Receiver did not select any offers from: "+
JSON.stringify(a));d.w=!!c.h;d.o=function(a,c){a==d.b?d.l.Ee("Audio stream (id="+a+") error: "+c):a==d.f&&d.l.Ee("Video stream (id="+a+") error: "+c)};by.rtpStream.onError.addListener(d.o);return ky(d,c,b)})}).then(function(){d.m.info(function(){return"Launched streaming for "+fy(d)});d.l.ag(d);ay(e,2);return{uo:d.b,Ar:d.f}})})};
dy.prototype.stop=function(){var a=this;return Zx(this.B,function(b){if(!a.h&&!a.j)return ay(b,1),Promise.resolve();a.m.info(function(){return"Stopping streaming for "+fy(a)+"."});a.o&&(by.rtpStream.onError.removeListener(a.o),a.o=null);if(a.l){var c=a.l.Ng();a.l=null}else c=Promise.resolve();return c.then(function(){a.b&&(by.rtpStream.stop(a.b),by.rtpStream.destroy(a.b),a.b=null);a.f&&(by.rtpStream.stop(a.f),by.rtpStream.destroy(a.f),a.f=null);a.A&&(by.udpTransport.destroy(a.A),a.A=null);a.Ca();
a.m.info(function(){return"Stopped streaming for "+fy(a)+"."});a.h=null;a.j=null;ay(b,1)})})};
var ly=function(a,b){var c=JSON.stringify(b);return Promise.all([a.b&&new Promise(function(b){return by.rtpStream.getRawEvents(a.b,c,b)}),a.f&&new Promise(function(b){return by.rtpStream.getRawEvents(a.f,c,b)})]).catch(function(c){a.m.error("Unexpected error when calling getRawEvents()",c);return[]}).then(function(a){return new Blob(a.filter(function(a){return!!a}),{type:"application/gzip"})})},my=function(a){return Promise.all([a.b&&new Promise(function(b){return by.rtpStream.getStats(a.b,b)}),a.f&&
new Promise(function(b){return by.rtpStream.getStats(a.f,b)})]).catch(function(b){a.m.error("Unexpected error when calling getStats()",b);return[]}).then(function(a){return Object.assign.apply(Object,[{}].concat(m(a.filter(function(a){return!!a}))))})},fy=function(a){if(a.h&&a.j)var b="audio+video ";else if(a.h)b="audio-only ";else if(a.j)b="video-only ";else return"stopped";return a.h instanceof ey||a.j instanceof ey?b+"remoting":b+"streaming"},gy=function(a){return new Promise(function(b){var c=
function(c,e,f){c&&!a.h&&(by.rtpStream.destroy(c),c=null);e&&!a.j&&(by.rtpStream.destroy(e),e=null);a.m.info(function(){return"Created Cast Streaming session: audioStreamId="+c+", videoStreamId="+e+"."});a.b=c;a.f=e;a.A=f;b()};a.h instanceof ey||a.j instanceof ey?by.session.create(null,null,c):by.session.create(a.h,a.j,c)})};
dy.prototype.C=function(){for(var a=fh(),b=fh(),c=[],d=k([this.b,this.f]),e=d.next();!e.done;e=d.next())if(e=e.value)for(var f=e==this.b,h=f?127:96,l=f?Math.floor(499999*Math.random())+1:Math.floor(499999*Math.random())+500001,r=f?48E3:9E4,y=k(by.rtpStream.getSupportedParams(e)),B=y.next();!B.done;B=y.next())B=B.value,B.payload.payloadType=h,B.payload.maxLatency=this.g.maxLatencyMillis,B.payload.minLatency=this.g.minLatencyMillis,B.payload.animatedLatency=this.g.animatedLatencyMillis,B.payload.ssrc=
l,B.payload.clockRate=r,B.payload.aesKey=a,B.payload.aesIvMask=b,f?(B.payload.channels=2,B.payload.maxBitrate=this.g.audioBitrate,B.payload.maxFrameRate=100):(B.payload.minBitrate=this.g.minVideoBitrate,B.payload.maxBitrate=this.g.maxVideoBitrate,B.payload.maxFrameRate=this.g.maxFrameRate),c.push(new ny(e,B));return c};
var jy=function(a,b,c){b&&!c.some(function(a){return a.Lf==b})&&(a.m.F("Destroying RTP stream not selected by the receiver: id="+b),by.rtpStream.destroy(b),b=null);return b},hy=function(a,b){return new Promise(function(c,d){for(var e=[],f=0;f<b.length;++f){var h=b[f].params,l={index:f,codecName:h.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:h.payload.payloadType,ssrc:h.payload.ssrc,targetDelay:h.payload.animatedLatency,aesKey:h.payload.aesKey,aesIvMask:h.payload.aesIvMask,timeBase:"1/"+
h.payload.clockRate,receiverRtcpEventLog:a.g.enableLogging,rtpExtensions:["adaptive_playout_delay"]};a.g.dscpEnabled&&(l.receiverRtcpDscp=46);127==h.payload.payloadType?Object.assign(l,{type:"audio_source",bitRate:0<h.payload.maxBitrate?1E3*h.payload.maxBitrate:60*h.payload.maxFrameRate+h.payload.clockRate*h.payload.channels,sampleRate:h.payload.clockRate,channels:h.payload.channels}):Object.assign(l,{type:"video_source",renderMode:"video",maxFrameRate:Math.round(1E3*h.payload.maxFrameRate)+"/1000",
maxBitRate:1E3*h.payload.maxBitrate,resolutions:[{width:a.g.maxWidth,height:a.g.maxHeight}]});e.push(l)}var r=a.h instanceof ey||a.j instanceof ey?"remoting":"mirroring",y={type:"OFFER",sessionId:a.G,seqNum:zk(a.N),offer:{castMode:r,receiverGetStatus:!0,supportedStreams:e}};a.m.info(function(){return"Sending OFFER message: "+JSON.stringify(y)});Ux(a.D,y,"ANSWER",1E4,function(b,e){if(null==b)d(e);else if("ok"==b.result&&b.b){if(b.f!=y.seqNum)return a.m.F("Ignoring ANSWER for OFFER with different seqNum: "+
JSON.stringify(b)),!1;((e=b.b.g)&&e!=r||!e&&"mirroring"!=r)&&a.m.error("Expected receiver to ANSWER with castMode="+r+", but got: "+e);nb(a.m,function(){return"Received ANSWER: "+JSON.stringify(b)});c(b.b)}else d(Error("Non-OK ANSWER received: "+JSON.stringify(b)));return!0})})},iy=function(a,b,c){if(b.b.length!=b.f.length)return a.m.error("sendIndexes.length != ssrcs.length in ANSWER: "+JSON.stringify(b)),[];for(var d=[],e={},f=0;f<b.b.length;e={Oe:e.Oe},++f){var h=b.b[f];if(0>h||h>=c.length)return a.m.error("Receiver selected invalid index ("+
h+" < "+c.length+") in ANSWER: "+JSON.stringify(b)),[];e.Oe=c[h];if(d.some(function(a){return function(c){return c.Lf==a.Oe.Lf}}(e)))return a.m.error("Receiver selected same RTP stream twice in ANSWER: "+JSON.stringify(b)),[];e.Oe.params.payload.feedbackSsrc=b.f[h];if(d.some(function(a){return function(c){return c.params.payload.feedbackSsrc==a.Oe.params.payload.feedbackSsrc}}(e)))return a.m.error("Receiver provided same SSRC for two different RTP streams in ANSWER: "+JSON.stringify(b)),[];d.push(e.Oe)}return d},
ky=function(a,b,c){var d=null,e=function(){d&&(by.rtpStream.onStarted.removeListener(d),d=null)};return(new Promise(function(e,h){var f=b.j||2344;a.m.info(function(){return"Starting RTP streams to receiver at "+(a.u+":"+f)+(" for selected offers: "+JSON.stringify(c))});var r=a.A||-1;a.g.dscpEnabled&&(a.m.info("Enabled DSCP in sender."),by.udpTransport.setOptions(r,{DSCP:!0}));by.udpTransport.setDestination(r,{address:a.u,port:f});var y=new Set(c.map(function(a){return a.Lf}));d=function(a){y.delete(a);
0==y.size&&e()};by.rtpStream.onStarted.addListener(d);r=k(c);for(var B=r.next();!B.done;B=r.next())B=B.value,by.rtpStream.toggleLogging(B.Lf,a.g.enableLogging),by.rtpStream.start(B.Lf,B.params);setTimeout(function(){h(Error("Timeout: RTP streams failed to start."))},1E4)})).then(e).catch(function(a){e();throw a;})},cy=function(a,b,c){var d=this;return a&&b in a?function(){try{a[b](c)}catch(e){d.m.error("Error from testHooks."+b,e)}}:function(){}},ny=function(a,b){this.Lf=a;this.params=b},ey=function(){};var qy=function(a,b,c,d,e,f){this.o=a;this.D=oy(b,this.o.ib);this.N=new dy(this.o.ib,c,d,e,f);this.w=e;this.j=new Vx;this.g=new py;this.B=new mojo.Binding(mojo.MirrorServiceRemoter,this,null);this.m=gb("mr.mirror.cast.MediaRemoter");this.u=this.b=this.l=this.h=this.C=null;this.f=!0;this.A=this.G.bind(this)};
qy.prototype.initialize=function(a,b){var c=this;return Xx(this.j,1,function(d){c.C=a;c.h=b;var e=c.B.createInterfacePtrAndBind();c.B.setConnectionErrorHandler(function(){c.m.info("Remoter mojo pipe connection error.");ry(c)});c.b=new mojo.MirrorServiceRemotingSourcePtr;var f=yg(c.o.mediaSource||"");if(!f)throw Error("Failed to parse tab ID from source:\n          "+c.o.mediaSource);c.m.info("Connecting remoter to browser: tabId="+f);(eg.get("mr.ProviderManager")||null).onMediaRemoterCreated(f,e,
mojo.makeRequest(c.b));c.b.ptr.setConnectionErrorHandler(function(){c.m.info("RemotingSource mojo pipe connection error.");ry(c)});return sy(c).then(function(){if(c.f)c.b.onSinkAvailable(c.D);ay(d,2)})})};
var ry=function(a){return Zx(a.j,function(b){a.b&&(a.b.ptr.reset(),a.b=null);var c=a.l;a.l=null;a.h=null;a.C=null;a.B.close();chrome.settingsPrivate.onPrefsChanged.hasListener(a.A)&&chrome.settingsPrivate.onPrefsChanged.removeListener(a.A);return new Promise(function(d){window.setTimeout(function(){ty(a).then(function(){ay(b,1);d();c&&c()})},250)})})};g=qy.prototype;g.cr=function(a){uy(this.g,a)};g.ag=function(a){this.h&&this.h.ag(a)};g.Ng=function(){return this.h?this.h.Ng():Promise.resolve()};
g.Ee=function(a,b){this.m.error("Error during streaming: "+a,b);if(this.b)this.b.onError();ry(this)};
g.start=function(){var a=this,b=!1;this.m.info(function(){b=!0;return"Starting next media remoting session."});b&&vy(this.g,function(c){return a.m.info(c)});wy(this.g);Xx(this.j,2,function(c){return(0,a.C)().then(function(b){a.l=b;Sx(a.w,"RPC",function(c){if(c.rpc){var b=a.g;c=c.rpc;b.l&&(++b.o,b.f+=c.length,b.l(c))}});ay(c,3)}).catch(function(b){return ty(a).then(function(){ay(c);throw b;})})}).then(function(){a.m.info("Remoting started successfully.")}).catch(function(c){a.m.error("Failed to start remoting",c);
a.b.onError()})};g.tr=function(a,b){var c=this;return Xx(this.j,3,function(d){return c.N.start(a?new ey:null,b?new ey:null,c).then(function(a){xy(c.g,function(a){return c.w.sendMessage(a)},function(a){c.b.onMessageFromSink(a)});ay(d,4);return{audio_stream_id:a.uo||-1,video_stream_id:a.Ar||-1}}).catch(function(a){return ty(c).then(function(){ay(d);throw a;})})}).catch(function(a){c.m.error("Failed to start remoting streams",a);ry(c);return{audio_stream_id:-1,video_stream_id:-1}})};
g.stop=function(a){var b=this;Yx(this.j,function(c){b.b.onStopped(a);return ty(b).then(function(){b.m.info("Remoting stopped.");ay(c,5);(0,b.l)().then(function(){return Xx(b.j,5,function(a){if(b.b&&b.f)b.b.onSinkAvailable(b.D);ay(a,2);return Promise.resolve()})}).catch(function(a){throw a;});b.l=null})}).catch(function(a){b.m.error("Failed to stop remoting: ",a);ry(b)})};
g.Lo=function(){null===this.u&&(this.u=Be(this.o.ib.If).then(function(a){return a.f||!1}));return this.u.then(function(a){return{rate:(a?1E7:5E6)/8}})};
var ty=function(a){return a.N.stop().then(function(){Tx(a.w,"RPC");yy(a.g);zy(a.g)})},sy=function(a){return new Promise(function(b){chrome.settingsPrivate.getPref("media_router.media_remoting.enabled",function(c){chrome.runtime.lastError?a.m.error("Encountered error getting media remoting pref: "+JSON.stringify(chrome.runtime.lastError)):c.type!=chrome.settingsPrivate.PrefType.BOOLEAN?a.m.error("Pref value not a boolean: "+JSON.stringify(c)):(a.f=!!c.value,a.m.info("Initializing mediaRemotingEnabled_ with value read from pref: "+
a.f));chrome.settingsPrivate.onPrefsChanged.hasListener(a.A)||chrome.settingsPrivate.onPrefsChanged.addListener(a.A);b()})})};
qy.prototype.G=function(a){if(this.b){a=k(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"media_router.media_remoting.enabled"==b.key){if(b.type!=chrome.settingsPrivate.PrefType.BOOLEAN){this.m.error("Pref value not a boolean: "+JSON.stringify(b));break}a=!!b.value;if(this.f==a)break;this.f=a;this.m.info("mediaRemotingEnabled_ changed to: "+this.f);if(this.f)this.b.onSinkAvailable(this.D);else this.b.onStopped(mojo.RemotingStopReason.USER_DISABLED);break}}};
var oy=function(a,b){var c=this,d=new mojo.RemotingSinkMetadata;d.features=[];d.friendly_name=b.sr||"";d.audio_capabilities=[];d.video_capabilities=[];var e=mojo.RemotingSinkAudioCapability,f=mojo.RemotingSinkVideoCapability,h=d.audio_capabilities,l=d.video_capabilities,r=b.Od||"";(a.b||[]).forEach(function(a){switch(a){case "audio":h.push(e.CODEC_BASELINE_SET);break;case "aac":h.push(e.CODEC_AAC);break;case "opus":h.push(e.CODEC_OPUS);break;case "video":l.push(f.CODEC_BASELINE_SET);break;case "4k":l.push(f.SUPPORT_4K);
break;case "h264":l.push(f.CODEC_H264);break;case "vp8":l.push(f.CODEC_VP8);break;case "vp9":r.startsWith("Chromecast Ultra")&&l.push(f.CODEC_VP9);break;case "hevc":r.startsWith("Chromecast Ultra")&&l.push(f.CODEC_HEVC);break;default:c.m.info("Unknown mediaCap name: "+a)}});b.Od&&"Chromecast Ultra"==b.Od&&l.push(f.SUPPORT_4K);return d};qy.prototype.estimateTransmissionCapacity=qy.prototype.Lo;qy.prototype.stop=qy.prototype.stop;qy.prototype.startDataStreams=qy.prototype.tr;qy.prototype.start=qy.prototype.start;
qy.prototype.sendMessageToSink=qy.prototype.cr;
var py=function(){this.l=this.j=this.b=null;this.u=this.f=this.o=this.g=this.A=0;this.h=null},wy=function(a){a.b=[];Ay(a,performance.now())},xy=function(a,b,c){a.j=b;a.l=c;a.b?(b=a.b,a.b=null,b.forEach(function(c){return uy(a,c.data).then(c.er,c.cm)})):Ay(a,performance.now())},yy=function(a){if(a.b){var b=Error("Stop before delivering pending message");a.b.forEach(function(a){return a.cm(b)});a.b=null}a.j=null;a.l=null},uy=function(a,b){if(a.j){var c=btoa(String.fromCharCode.apply(null,b));++a.A;
a.g+=b.length;return a.j({type:"RPC",rpc:c})}return a.b?new Promise(function(c,e){a.b.push({data:b,er:c,cm:e})}):Promise.reject(Error("RPC pipe not started"))},vy=function(a,b){zy(a);a.h=setInterval(function(){if(a.b)var c=a.b.length+" messages are waiting to send.";else{c=performance.now();var d=(c-a.u)/1E3;d="Over the past "+d.toFixed(1)+" seconds, sent "+(a.A+" messages ("+Math.round(a.g/d)+" bytes/sec) and ")+("received "+a.o+" messages ("+Math.round(a.f/d)+" ")+"bytes/sec).";Ay(a,c);c=d}b(c)},
3E4)},zy=function(a){null!=a.h&&(clearInterval(a.h),a.h=null)},Ay=function(a,b){a.A=0;a.g=0;a.o=0;a.f=0;a.u=b};var By=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Cy=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Dy=function(a,b,c,d,e){this.g=new dy(a,b,c,d,void 0===e?null:e);this.m=gb("mr.mirror.cast.MediaStreamer");this.j=new Vx;this.h=this.f=this.b=this.l=null};Dy.prototype.start=function(a,b){var c=this;return Xx(this.j,1,function(d){c.l=a;c.b=By(a);c.b&&"ended"==c.b.readyState&&(c.b=null);c.f=Cy(a);c.f&&"ended"==c.f.readyState&&(c.f=null);if(!c.b&&!c.f)return ay(d),Promise.reject(Error("No MediaStream tracks to stream."));c.h=b;return c.g.start(c.b,c.f,c.h).then(function(){return ay(d,2)})})};
Dy.prototype.stop=function(){var a=this;return Zx(this.j,function(b){return a.g.stop().then(function(){a.b=null;a.f=null;a.l=null;a.h=null;ay(b,1)})})};var Ey=function(a){return Xx(a.j,2,function(b){a.m.info("Suspending media streaming...");return a.g.stop().then(function(){a.m.info("Suspended media streaming.");ay(b,3)})})};
Dy.prototype.resume=function(){var a=this;return Xx(this.j,3,function(b){a.b&&"ended"==a.b.readyState&&(a.b=null);a.f&&"ended"==a.f.readyState&&(a.f=null);if(!a.b&&!a.f)return Promise.reject(Error("Cannot resume: All tracks have ended."));a.m.info("Resuming media streaming...");return a.g.start(a.b,a.f,a.h).then(function(){a.m.info("Resumed media streaming.");ay(b,2)})})};var Fy=function(a,b,c){this.j=a;this.h=b;this.g=c;this.m=gb("mr.mirror.cast.WifiStatusMonitor");this.b=null;this.f=[]};Fy.prototype.start=function(){var a=this;null==this.b&&(nb(this.m,"Starting Wifi Status Monitoring."),this.f=[],Sx(this.g,"STATUS_RESPONSE",function(b){return Gy(a,b)}),this.b=setInterval(function(){return Hy(a)},12E4),Hy(this))};Fy.prototype.stop=function(){null!=this.b&&(nb(this.m,"Stopping Wifi Status Monitoring."),clearInterval(this.b),this.b=null,Tx(this.g,"STATUS_RESPONSE"))};
var Gy=function(a,b){if(null!=a.b)if(b.status){var c={};null!=b.status.b&&(c.wifiSnr=b.status.b);null!=b.status.f&&(c.wifiSpeed=b.status.f[3]);0==Object.keys(c).length?a.m.F(function(){return"No status fields populated in response: "+JSON.stringify(b)}):(c.timestamp=Date.now(),30==a.f.length&&a.f.shift(),a.f.push(c),a.m.info(function(){return"Current Wifi status: "+JSON.stringify(c)}))}else a.m.F(function(){return"Ignoring response without status: "+JSON.stringify(b)})},Hy=function(a){a.g.sendMessage({type:"GET_STATUS",
sessionId:a.j,seqNum:zk(a.h),get_status:["wifiSnr","wifiSpeed"]})};var Iy=function(a,b,c,d){this.D=b.If;this.o={extVersion:chrome.runtime.getManifest().version,extChannel:"public",mirrorSettings:Ng(a),sender:navigator.userAgent||"UNKNOWN",receiverProductName:b.Od};this.C=c;this.w=d;this.h=this.f=this.A=this.l=this.j=this.u=this.g=null;this.b=[]};Iy.prototype.ag=function(a){null!=this.f&&clearInterval(this.f);this.g=a;this.u=Date.now();this.f=setInterval(this.B.bind(this,a),9E5)};
Iy.prototype.Ng=function(){null!=this.f&&(clearInterval(this.f),this.f=null);if(null!=this.g){var a=this.B(this.g);this.g=null;return a}return Promise.resolve()};Iy.prototype.Ee=function(a,b){null==this.j&&(this.j=Date.now(),"function"===typeof a?this.l=a():"string"===typeof a&&(this.l=a),b&&"string"===typeof b.stack&&(this.A=b.stack))};
var Ky=function(a,b){return(null==a.g?Promise.resolve():a.B(a.g)).then(function(){var c=b.map(function(c){c=Jy(a,c);var b=c.map(function(a){return a.events}).filter(function(a){return null!=a}),d=["["];c.map(function(a){return a.Kf}).forEach(function(a,c){0<c&&d.push(",");d.push(a)});d.push("]");return{events:new Blob(b,{type:"application/gzip"}),Kf:new Blob(d,{type:"application/json"})}});a.b=[];return c})};
Iy.prototype.B=function(a){var b=this;if(null!=this.h)return this.h;var c=Be(this.D).then(function(c){c={receiverVersion:c.b,receiverConnected:c.h,receiverOnEthernet:c.f,receiverHasUpdatePending:c.g,receiverUptimeSeconds:c.j};Object.assign(c,b.o);var d=Date.now();Object.assign(c,{startTime:b.u,endTime:d,activity:fy(a),receiverWifiStatus:Array.from(b.w.f)});b.u=d;null!=b.j&&(Object.assign(c,{streamingErrorTime:b.j,streamingErrorMessage:b.l,streamingErrorCause:b.A}),b.j=null,b.l=null,b.A=null);return c});
return(this.h=Promise.all([c.then(function(c){return ly(a,c)}),c,my(a)]).then(function(a){var c=k(a);a=c.next().value;var d=c.next().value;c=c.next().value;b.b.push({events:a,Kf:new Blob([JSON.stringify(Object.assign({tags:d},c))],{type:"application/json"})});b.b=Jy(b,b.C);b.h=null}))||Promise.resolve()};
var Jy=function(a,b){b-=2;for(var c=[],d=a.b.length-1;0<=d;--d){b-=a.b[d].Kf.size+1;if(0>b)break;c.push({events:null,Kf:a.b[d].Kf});if(null!=a.b[d].events){var e=a.b[d].events.size;b>=e&&(c[c.length-1].events=a.b[d].events,b-=e)}}return c.reverse()};var Ly=gb("mr.NetworkUtils"),My=function(a,b){return Qf?new Promise(function(c,d){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(Ly.F("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),d("Unable to set TDLS state to "+b+".")):(Ly.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Ny=function(a,b,c,d){d=void 0===d?null:d;Kg.call(this,b);var e=b.ib;this.B=e.sessionId;this.G=e.If;this.N=a;this.K=d;this.m=gb("mr.mirror.cast.Session");this.u=new Vx;this.A=new yk("mirror.cast.SeqNumGenerator");this.o=new Rx(b.id);this.l=new Dy(e,this.N,this.A,this.o,this.K);this.h=null;this.b=new Iy(a,e,c,new Fy(this.B,this.A,this.o));this.g=!1;this.w=null};n(Ny,Kg);g=Ny.prototype;
g.start=function(a){var b=this;return Xx(this.u,1,function(c){var d=new rb("MediaRouter.CastStreaming.Session.Launch");return Oy(b).then(function(c){b.g=c;return b.l.start(a,b)}).then(function(){if(b.l.g.w){var a=b.b;a.o.tdlsIsOn=b.g;a.w.start();Py(b)}else b.b.o.tdlsIsOn=b.g;d.b();b.w=new xb("MediaRouter.CastStreaming.Session.Length");ay(c,2);return b})})};
g.stop=function(){var a=this;return Zx(this.u,function(b){a.w&&(a.w.b(),a.w=null);a.b.w.stop();return a.l.stop().then(function(){return a.h?ry(a.h):Promise.resolve()}).then(function(){a.h=null;return a.g?Qy(a):Promise.resolve()}).then(function(){a.g=!1;ay(b,4)})})};g.am=function(){var a={sessionId:this.B,seqNum:zk(this.A),type:"PRESENTATION",icons:[],title:Ig(this.bc)};this.m.info("Sending session metadata update to receiver: "+this.B);this.o.sendMessage(a)};g.ag=function(a){this.b.ag(a)};g.Ng=function(){return this.b.Ng()};
g.Ee=function(a,b){this.b.Ee(a,b);this.m.error(a,b);this.stop()};
var Ry=function(a,b){return Ky(a.b,b)},Oy=function(a){return a.N.useTdls?My(a.G,!0).then(function(b){if("Connected"==b)return a.m.info("Successfully enabled TDLS."),!0;a.m.F("Did not enable TDLS: result="+b);return!1}).catch(function(b){a.m.F("Error while calling enableTDLS()",b);return!1}):Promise.resolve(!1)},Qy=function(a){return My(a.G,!1).catch(function(b){return a.m.error("Error while turning TDLS back off",b)})},Py=function(a){Sy(a).then(function(b){(b.b||[]).includes("video")?Ty(a,b):a.m.F(function(){return"Receiver incapable of Media Remoting: "+
JSON.stringify(b)})}).catch(function(b){a.m.F("None/Invalid capabilites response. Media Remoting disabled.",b)})},Sy=function(a){return new Promise(function(b,c){var d={type:"GET_CAPABILITIES",sessionId:a.B,seqNum:zk(a.A)};a.m.info(function(){return"Sending GET_CAPABILITIES message: "+JSON.stringify(d)});Ux(a.o,d,"CAPABILITIES_RESPONSE",3E4,function(e,f){if(null==e)return c(f),!0;if("ok"!=e.result||!e.capabilities)return c(Error("Bad response: "+JSON.stringify(e))),!0;if(e.f!=d.seqNum)return a.m.info(function(){return"Ignoring CAPABILITIES_RESPONSE with different seqNum: "+
JSON.stringify(e)}),!1;nb(a.m,function(){return"Received CAPABILITIES_RESPONSE: "+JSON.stringify(e)});b(e.capabilities);return!0})})},Ty=function(a,b){Xx(a.u,2,function(c){var d=a.f.ib.Od||"<UNKNOWN>";if(!d.startsWith("Chromecast")&&!d.startsWith("Eureka Dongle"))return a.m.F("HACK: Media Remoting disabled because the receiver model--"+('"'+d+'" according to discovery--is not a Chromecast.')),ay(c),Promise.resolve();a.h=new qy(a.f,b,a.N,a.A,a.o,a.K);return a.h.initialize(a.M.bind(a),a).catch(function(c){a.m.error("Media Remoting start failed: "+
c.message,c)}).then(function(){return ay(c)})})};Ny.prototype.M=function(){var a=this;return Xx(this.u,2,function(b){return new Promise(function(c,d){Ey(a.l).then(function(){ay(b,3);a.D=!0;Eg(a);c(a.Ca.bind(a))}).catch(function(c){a.Ee("Failed to suspend MediaStreamer before starting remoting",c);d(c)})})})};
Ny.prototype.Ca=function(){var a=this;return Xx(this.u,3,function(b){return new Promise(function(c,d){a.l.resume().then(function(){ay(b,2);a.D=!1;Eg(a);c()}).catch(function(c){a.Ee("Failed resume MediaStreamer after ending remoting mode",c);d(c)})})})};var Uy=function(){zg.call(this,"cast_streaming");this.j=this.A=this.D=this.C=this.h=null;this.G=this.N="";this.K=this.o=!1;this.Ca=this.da.bind(this);this.B=null};n(Uy,zg);g=Uy.prototype;g.bg=function(a){this.o=a||!1;this.K=!0};g.getName=function(){return"cast_streaming"};
g.Zi=function(a,b,c,d,e){var f=this;if(!this.o)return zg.prototype.Zi.call(this,a,b,c,d,e);this.L.info("Start mirroring on route "+a.id);if(!this.K)return Jf(Error("Not initialized"));var h=new Promise(function(h,r){f.l().then(function(){if(tg(b)&&c.shouldCaptureVideo)return(new Promise(function(c){chrome.tabs.get(a.ib.tabId||-1,c)})).then(function(a){return bg(a).then(function(a){f.G=a})})}).then(function(){return e?e(a).b:a}).then(function(a){f.C=new mojo.Binding(mojo.MirroringSessionObserver,f,
null);f.D=new mojo.Binding(mojo.MirroringCastMessageChannel,f,null);f.j=ow(a.id);f.j.onMessage=f.Op.bind(f);var e=f.C.createInterfacePtrAndBind(),l=f.D.createInterfacePtrAndBind(),r=Vy(a,c);f.h=new mojo.MirroringServiceHostPtr;var y=a.ib.tabId||-1;sg(b)?f.g.getMirroringServiceHostForTab(y,mojo.makeRequest(f.h)):tg(b)?f.g.getMirroringServiceHostForDesktop(y,f.G,mojo.makeRequest(f.h)):wg(b)?(y=new mojo.Url,y.url=b,f.g.getMirroringServiceHostForOffscreenTab(y,d||"",mojo.makeRequest(f.h))):f.h=null;if(!f.h)throw new Nf("Error to get mirroring service host");
f.A=new mojo.MirroringCastMessageChannelPtr;f.h.start(r,e,l,mojo.makeRequest(f.A));f.B=new Kg(a);e=f.g.Ai.bind(f.g);f.B.C=e;sg(b)&&!chrome.tabs.onUpdated.hasListener(f.Ca)&&chrome.tabs.onUpdated.addListener(f.Ca);(sg(b)||wg(b))&&Dg(f.B,a.ib.tabId);h(a)}).catch(function(a){f.L.info("Mirroring launch error: "+a);r(a)})});return Kf(h)};g.eh=function(a,b){return new Ny(a,b,20969472,null)};g.Fg=function(){rx(0)};g.Cg=function(){rx(1)};g.Hh=function(){rx(2)};g.Dg=function(){Ab("MediaRouter.CastStreaming.Session.End")};
g.Gh=function(a){Bb("MediaRouter.CastStreaming.Start.Failure",a,Mf)};g.Eg=function(){Ab("MediaRouter.CastStreaming.Stream.End")};
g.hi=function(a){var b=this;return this.o?Promise.resolve():(new Promise(function(a){return chrome.metricsPrivate.getIsCrashReportingEnabled(a)})).then(function(c){var d=c&&yx(),e=[9351424];d&&e.push(20969472);return Ry(a,e).then(function(a){var e=a[a.length-1];a=tj(a[0].events).catch(function(a){b.L.error("Failed to persist events Blob.",a)});d&&0<e.events.size?ux(e.events,void 0,b.Np.bind(b)):c&&tx("stats.json",e.Kf,void 0,void 0);return a})})};g.Np=function(a){a&&(xx().b=Date.now())};
g.Yi=function(a){if(this.o)return db();this.L.info("Received message to upload logs for "+a);return this.b?Ry(this.b,[20969472]).then(function(b){b=k(b).next().value;return 0==b.events.size?"":ux(b.events,a)}):Promise.resolve(Wy(this,a))};
var Wy=function(a,b){var c=window.localStorage.getItem("mr.temp.mirror.cast.Service.eventsBlob");if(null==c||1>c.length)c=null;else{for(var d=new Uint16Array(c.length),e=0;e<c.length;++e)d[e]=c.charCodeAt(e);c=d.buffer;d=(new Uint8Array(c,c.byteLength-1,1))[0];c=new Uint8Array(c,0,c.byteLength-(0==d?2:1));c=new Blob([c],{type:"application/gzip"})}if(null!=c&&0!=c.size)return tj(new Blob),a.L.info("Uploading saved logs for feedback."),ux(c,b)};g=Uy.prototype;
g.onError=function(a){this.L.info("Mirroring service error: "+a);this.l()};g.didStart=function(){sg(this.N)?this.Fg():tg(this.N)?this.Cg():wg(this.N)&&this.Hh()};g.didStop=function(){this.l()};g.send=function(a){if(this.j){var b=JSON.parse(a.jsonFormatData);nb(this.L,function(){return"Sending message: "+JSON.stringify(b)});this.j.sendMessage(a.jsonFormatData,{namespace:a.messageNamespace})}};
g.Op=function(a){if(a&&(a.namespace_===mojo.MirroringWebRtcNamespace||a.namespace_===mojo.MirroringRemotingNamespace)&&this.A){var b=new mojo.MirroringCastMessage;b.messageNamespace=a.namespace_;"string"!==typeof a.data?this.L.info("Received non-string as JSON"):(b.jsonFormatData=a.data,this.A.send(b))}};
var Vy=function(a,b){var c=new mojo.MirroringSessionParameters;c.receiverAddress=new mojo.IPAddress;c.receiverAddress.addressBytes=a.ib.If.split(".").map(function(a){return parseInt(a,10)});c.receiverModelName=a.ib.Od;c.type=b.shouldCaptureVideo&&b.shouldCaptureAudio?mojo.MirroringSessionType.AUDIO_AND_VIDEO:b.shouldCaptureVideo?mojo.MirroringSessionType.VIDEO_ONLY:mojo.MirroringSessionType.AUDIO_ONLY;return c};Uy.prototype.da=function(a,b,c){rg(14);this.B&&Fg(this.B,a,b,c)};
Uy.prototype.l=function(){chrome.tabs.onUpdated.removeListener(this.Ca);return this.o?this.K?this.h?(this.h.ptr.reset(),this.A=this.h=null,this.j&&this.j.Ua(),this.j=null,this.C&&(this.C.close(),this.C=null),this.D&&(this.D.close(),this.D=null),this.G=this.N="",this.Dg(),Promise.resolve(!0)):Promise.resolve(!1):Promise.reject("Not initialized"):zg.prototype.l.call(this)};
Uy.prototype.aj=function(a,b,c,d,e,f){return this.o?Jf(Error("Mirroring service does not support updating stream")):zg.prototype.aj.call(this,a,b,c,d,e,f)};Uy.prototype.send=Uy.prototype.send;Uy.prototype.didStop=Uy.prototype.didStop;Uy.prototype.didStart=Uy.prototype.didStart;Uy.prototype.onError=Uy.prototype.onError;var Xy=new Uy;og("mr.mirror.cast.Service",Xy);
